/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/learning` | `/learning`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/projects` | `/projects`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/showcase` | `/showcase`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/learning` | `/learning`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/projects` | `/projects`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/showcase` | `/showcase`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/learning${`?${string}` | `#${string}` | ''}` | `/learning${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/projects${`?${string}` | `#${string}` | ''}` | `/projects${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/showcase${`?${string}` | `#${string}` | ''}` | `/showcase${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/learning` | `/learning`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/projects` | `/projects`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/showcase` | `/showcase`; params?: Router.UnknownInputParams; };
    }
  }
}
