/**
 * Email Service
 * Handles all email sending using Brevo REST API (HTTP - works on Render)
 * Uses Node.js built-in fetch (Node 18+) — no extra dependencies
 */

class EmailService {
    constructor() {
        this.apiKey = process.env.BREVO_API_KEY;
        this.apiUrl = 'https://api.brevo.com/v3/smtp/email';
        this.defaultFrom = {
            email: process.env.EMAIL_FROM || 'alpha4coders@gmail.com',
            name: process.env.EMAIL_FROM_NAME || 'DevTrack',
        };
        console.log('📧 Email service initialized with Brevo');
    }

    /**
     * Send an email via Brevo REST API
     * @param {Object} options
     * @param {string} options.to - Recipient email
     * @param {string} options.subject - Email subject
     * @param {string} options.html - HTML content
     * @param {string} [options.from] - Sender email (optional)
     * @param {Array}  [options.attachments] - Array of attachment objects
     * @returns {Promise<Object>} - Send result
     */
    async sendEmail({ to, subject, html, from, attachments = [] }) {
        try {
            if (!this.apiKey) {
                throw new Error('BREVO_API_KEY is not configured');
            }

            const payload = {
                sender: from
                    ? { email: from }
                    : this.defaultFrom,
                to: [{ email: to }],
                subject,
                htmlContent: html,
            };

            if (attachments.length > 0) {
                payload.attachment = attachments.map(att => ({
                    name: att.filename,
                    content: att.content, // base64 string
                }));
            }

            const response = await fetch(this.apiUrl, {
                method: 'POST',
                headers: {
                    'api-key': this.apiKey,
                    'Content-Type': 'application/json',
                    'Accept': 'application/json',
                },
                body: JSON.stringify(payload),
            });

            const result = await response.json();

            if (!response.ok) {
                const errMsg = result.message || `HTTP ${response.status}`;
                console.error(`❌ Brevo error sending to ${to}:`, errMsg);
                return { success: false, error: errMsg };
            }

            console.log(`✅ Email sent to ${to}, messageId: ${result.messageId}`);
            return { success: true, messageId: result.messageId };
        } catch (error) {
            console.error(`❌ Failed to send email to ${to}:`, error.message);
            return { success: false, error: error.message };
        }
    }

    /**
     * Send weekly report email with PDF attachment
     * @param {string} to - Recipient email
     * @param {string} userName - User's name for greeting
     * @param {Buffer} pdfBuffer - PDF report buffer
     * @returns {Promise<Object>}
     */
    async sendWeeklyReport(to, userName, pdfBuffer) {
        const subject = `Your Weekly GitHub Report - ${new Date().toLocaleDateString()}`;
        const html = `
            <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; background: #0f172a; padding: 40px; border-radius: 16px;">
                <h1 style="color: #6366f1; margin-bottom: 8px;">Weekly DevTrack Report</h1>
                <p style="color: #94a3b8; margin-bottom: 24px;">Hi ${userName},</p>
                <p style="color: #e2e8f0;">Your weekly GitHub activity report is attached as a PDF.</p>
                <p style="color: #e2e8f0;">Keep up the great work and maintain your coding streak!</p>
                <hr style="border: 1px solid #1e293b; margin: 24px 0;">
                <p style="color: #64748b; font-size: 12px;">Generated by DevTrack - Your Developer Consistency Tracker</p>
            </div>
        `;

        return this.sendEmail({
            to,
            subject,
            html,
            attachments: [{
                filename: `devtrack-report-${new Date().toISOString().split('T')[0]}.pdf`,
                content: pdfBuffer.toString('base64'),
                encoding: 'base64',
            }],
        });
    }

    /**
     * Send comment notification email
     * @param {string} to - Project owner's email
     * @param {string} projectName - Name of the project
     * @param {string} commenterName - Name of the person who commented
     * @param {string} commentContent - The comment content (already escaped)
     * @returns {Promise<Object>}
     */
    async sendCommentNotification(to, projectName, commenterName, commentContent) {
        const subject = `💬 New comment on "${projectName}"`;
        const html = `
            <div style="font-family: system-ui, sans-serif; max-width: 600px; margin: 0 auto;">
                <h2 style="color: #7c3aed;">New Comment on Your Showcase</h2>
                <p><strong>${commenterName}</strong> commented on your project <strong>"${projectName}"</strong>:</p>
                <blockquote style="border-left: 4px solid #7c3aed; padding-left: 16px; margin: 16px 0; color: #374151;">
                    ${commentContent}
                </blockquote>
                <p style="color: #6b7280; font-size: 14px;">View your showcase on DevTrack to reply.</p>
            </div>
        `;

        return this.sendEmail({ to, subject, html });
    }

    /**
     * Verify Brevo configuration
     * @returns {Promise<boolean>}
     */
    async verifyConnection() {
        if (!this.apiKey) {
            console.error('❌ BREVO_API_KEY is not set!');
            return false;
        }
        console.log('✅ Brevo API key is configured');
        return true;
    }
}

module.exports = new EmailService();
