/**
 * Email Service
 * Handles all email sending using Nodemailer with Gmail SMTP
 */

const nodemailer = require('nodemailer');

class EmailService {
    constructor() {
        // Use SSL (port 465) for reliable delivery on cloud platforms
        const port = parseInt(process.env.SMTP_PORT) || 465;
        const secure = port === 465; // true for SSL

        this.transporter = nodemailer.createTransport({
            host: process.env.SMTP_HOST || 'smtp.gmail.com',
            port: port,
            secure: secure,
            auth: {
                user: process.env.SMTP_USER,
                pass: process.env.SMTP_PASS,
            },
            connectionTimeout: 30000, // 30 seconds
            greetingTimeout: 30000,
            socketTimeout: 30000,
        });

        this.defaultFrom = process.env.EMAIL_FROM || 'DevTrack <alpha4coders@gmail.com>';
    }

    /**
     * Send an email
     * @param {Object} options - Email options
     * @param {string} options.to - Recipient email
     * @param {string} options.subject - Email subject
     * @param {string} options.html - HTML content
     * @param {string} [options.from] - Sender (optional, uses default)
     * @param {Array} [options.attachments] - Array of attachment objects
     * @returns {Promise<Object>} - Send result
     */
    async sendEmail({ to, subject, html, from, attachments = [] }) {
        try {
            const mailOptions = {
                from: from || this.defaultFrom,
                to,
                subject,
                html,
                attachments: attachments.map(att => ({
                    filename: att.filename,
                    content: att.content,
                    encoding: att.encoding || 'base64',
                })),
            };

            const result = await this.transporter.sendMail(mailOptions);
            console.log(`Email sent successfully to ${to}, messageId: ${result.messageId}`);
            return { success: true, messageId: result.messageId };
        } catch (error) {
            console.error(`Failed to send email to ${to}:`, error.message);
            return { success: false, error: error.message };
        }
    }

    /**
     * Send weekly report email with PDF attachment
     * @param {string} to - Recipient email
     * @param {string} userName - User's name for greeting
     * @param {Buffer} pdfBuffer - PDF report buffer
     * @returns {Promise<Object>} - Send result
     */
    async sendWeeklyReport(to, userName, pdfBuffer) {
        const subject = `Your Weekly GitHub Report - ${new Date().toLocaleDateString()}`;
        const html = `
            <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; background: #0f172a; padding: 40px; border-radius: 16px;">
                <h1 style="color: #6366f1; margin-bottom: 8px;">Weekly DevTrack Report</h1>
                <p style="color: #94a3b8; margin-bottom: 24px;">Hi ${userName},</p>
                <p style="color: #e2e8f0;">Your weekly GitHub activity report is attached as a PDF.</p>
                <p style="color: #e2e8f0;">Keep up the great work and maintain your coding streak!</p>
                <hr style="border: 1px solid #1e293b; margin: 24px 0;">
                <p style="color: #64748b; font-size: 12px;">
                    Generated by DevTrack - Your Developer Consistency Tracker
                </p>
            </div>
        `;

        return this.sendEmail({
            to,
            subject,
            html,
            attachments: [{
                filename: `devtrack-report-${new Date().toISOString().split('T')[0]}.pdf`,
                content: pdfBuffer.toString('base64'),
                encoding: 'base64',
            }],
        });
    }

    /**
     * Send comment notification email
     * @param {string} to - Project owner's email
     * @param {string} projectName - Name of the project
     * @param {string} commenterName - Name of the person who commented
     * @param {string} commentContent - The comment content (already escaped)
     * @returns {Promise<Object>} - Send result
     */
    async sendCommentNotification(to, projectName, commenterName, commentContent) {
        const subject = `💬 New comment on "${projectName}"`;
        const html = `
            <div style="font-family: system-ui, sans-serif; max-width: 600px; margin: 0 auto;">
                <h2 style="color: #7c3aed;">New Comment on Your Showcase</h2>
                <p><strong>${commenterName}</strong> commented on your project <strong>"${projectName}"</strong>:</p>
                <blockquote style="border-left: 4px solid #7c3aed; padding-left: 16px; margin: 16px 0; color: #374151;">
                    ${commentContent}
                </blockquote>
                <p style="color: #6b7280; font-size: 14px;">
                    View your showcase on DevTrack to reply.
                </p>
            </div>
        `;

        return this.sendEmail({ to, subject, html });
    }

    /**
     * Verify SMTP connection
     * @returns {Promise<boolean>} - Whether connection is working
     */
    async verifyConnection() {
        try {
            await this.transporter.verify();
            console.log('SMTP connection verified successfully');
            return true;
        } catch (error) {
            console.error('SMTP connection verification failed:', error.message);
            return false;
        }
    }
}

module.exports = new EmailService();
