/**
 * DevTrack Notification Service
 * ─────────────────────────────────────────────────────────────────────────
 * Handles ALL notification delivery:
 *   - FCM push (Firebase Cloud Messaging via firebase-admin)
 *   - In-app notification store (per-user array in Firestore user doc)
 *
 * AI content is generated by GroqNotificationService using the
 * dedicated GROQ_NOTIFICATION_API_KEY — separate from the main chat AI.
 * ─────────────────────────────────────────────────────────────────────────
 */

const { admin, collections } = require('../config/firebase');
const { getGroqNotificationService } = require('./groqNotificationService');
const GitHubService = require('./githubService');

// ─── In-app notification cap per user ────────────────────────────────────────
const MAX_IN_APP_NOTIFICATIONS = 50;

class NotificationService {
    constructor() {
        this.messaging = admin.messaging();
        this.groq = getGroqNotificationService();
    }

    // =========================================================================
    // CORE: SEND NOTIFICATION
    // =========================================================================

    /**
     * Send an FCM push notification to a specific device.
     * @param {string} fcmToken  - Device FCM token
     * @param {{ title, body }} notification
     * @param {object} data - Additional data payload
     */
    async sendPush(fcmToken, notification, data = {}) {
        if (!fcmToken) return { success: false, error: 'No FCM token' };

        try {
            const message = {
                token: fcmToken,
                notification: {
                    title: notification.title,
                    body: notification.body,
                },
                data: {
                    ...Object.fromEntries(
                        Object.entries(data).map(([k, v]) => [k, String(v)])
                    ),
                    click_action: 'OPEN_APP',
                },
                webpush: {
                    notification: {
                        icon: '/DevTrack.png',
                        badge: '/favicon.png',
                        vibrate: [200, 100, 200],
                    },
                    fcmOptions: {
                        link: process.env.CLIENT_URL || process.env.CORS_ORIGIN || 'https://devtrackweb.xyz',
                    },
                },
            };

            const response = await this.messaging.send(message);
            console.log('✅ Push sent:', response);
            return { success: true, messageId: response };
        } catch (error) {
            console.error('❌ Push failed:', error.message);
            if (
                error.code === 'messaging/invalid-registration-token' ||
                error.code === 'messaging/registration-token-not-registered'
            ) {
                return { success: false, error: 'invalid_token', shouldRemove: true };
            }
            return { success: false, error: error.message };
        }
    }

    /**
     * Save a notification to the user's in-app notifications array.
     * Keeps the array capped at MAX_IN_APP_NOTIFICATIONS (FIFO).
     * @param {string} userId
     * @param {{ title, body, type, data }} notif
     */
    async saveInApp(userId, notif) {
        try {
            const entry = {
                id: `notif_${Date.now()}_${Math.random().toString(36).substr(2, 7)}`,
                title: notif.title,
                body: notif.body,
                type: notif.type || 'general',
                data: notif.data || {},
                read: false,
                createdAt: new Date().toISOString(),
            };

            const userRef = collections.users().doc(userId);
            const userDoc = await userRef.get();
            if (!userDoc.exists) return;

            const existing = userDoc.data().notifications || [];
            // Prepend new, cap array
            const updated = [entry, ...existing].slice(0, MAX_IN_APP_NOTIFICATIONS);

            await userRef.update({ notifications: updated });
            return entry;
        } catch (error) {
            console.error('❌ Failed to save in-app notification:', error.message);
        }
    }

    /**
     * Full send: AI content → FCM push + in-app store.
     * @param {string}   userId
     * @param {string}   type      - notification type key
     * @param {Function} aiGen     - () => Promise<{title,body}>
     * @param {object}   data      - extra payload for FCM data + in-app data field
     * @param {object}   fallback  - { title, body } if AI fails
     */
    async send(userId, type, aiGen, data = {}, fallback = {}) {
        try {
            const userDoc = await collections.users().doc(userId).get();
            if (!userDoc.exists) return { success: false, error: 'User not found' };

            const user = userDoc.data();

            // Respect user notification opt-out
            if (user.preferences?.notifications === false) {
                return { success: false, error: 'Notifications disabled by user' };
            }

            // Generate AI content
            let content;
            try {
                content = await aiGen();
            } catch {
                content = null;
            }
            const notif = content || fallback || { title: 'DevTrack', body: 'You have a new notification.' };

            // 1. Save in-app
            await this.saveInApp(userId, { ...notif, type, data });

            // 2. FCM push (if token exists)
            let pushResult = { success: false, error: 'No FCM token' };
            if (user.fcmToken) {
                pushResult = await this.sendPush(user.fcmToken, notif, { type, ...data });

                // Clean up invalid token automatically
                if (pushResult.shouldRemove) {
                    await collections.users().doc(userId).update({
                        fcmToken: null,
                        fcmTokenUpdatedAt: new Date().toISOString(),
                    });
                }
            }

            return { success: true, notification: notif, push: pushResult };
        } catch (error) {
            console.error(`❌ send(${type}) failed for ${userId}:`, error.message);
            return { success: false, error: error.message };
        }
    }

    // =========================================================================
    // NOTIFICATION TYPE METHODS
    // =========================================================================

    /** Consistency reminder respecting onboarding preferences */
    async sendConsistencyReminder(userId) {
        const userDoc = await collections.users().doc(userId).get();
        if (!userDoc.exists) return { success: false, error: 'User not found' };
        const user = userDoc.data();
        const prefs = user.preferences || {};

        return this.send(
            userId,
            'consistency_reminder',
            () => this.groq.generateConsistencyReminder({
                userGoal: user.userGoal || 'coding',
                streak: user.streak || 0,
                reminderMode: prefs.reminderMode || 'adaptive',
                lastActive: user.updatedAt,
            }),
            { type: 'consistency_reminder', userGoal: user.userGoal || '' },
            { title: '🔥 Time to Code!', body: 'Keep your streak alive. Open your editor and ship something!' }
        );
    }

    /** Streak milestone notification */
    async sendStreakMilestone(userId, streak) {
        const userDoc = await collections.users().doc(userId).get();
        if (!userDoc.exists) return { success: false, error: 'User not found' };
        const user = userDoc.data();

        return this.send(
            userId,
            'streak_milestone',
            () => this.groq.generateStreakMilestone({
                userGoal: user.userGoal || 'coding',
                streak,
            }),
            { type: 'streak_milestone', streak: String(streak) },
            { title: `🏆 ${streak}-Day Streak!`, body: `You've been consistent for ${streak} days. Incredible!` }
        );
    }

    /** Showcase star notification (send to project owner) */
    async sendShowcaseStar(ownerId, starredByName, projectName, showcaseId, totalStars) {
        return this.send(
            ownerId,
            'showcase_star',
            () => this.groq.generateShowcaseStar({ projectName, starredByName, totalStars }),
            { type: 'showcase_star', showcaseId, projectName },
            { title: `⭐ ${starredByName} starred ${projectName}!`, body: `Your project now has ${totalStars} star${totalStars !== 1 ? 's' : ''}.` }
        );
    }

    /** Showcase comment notification (send to project owner) */
    async sendShowcaseComment(ownerId, commenterName, projectName, commentSnippet, showcaseId) {
        return this.send(
            ownerId,
            'showcase_comment',
            () => this.groq.generateShowcaseComment({ projectName, commenterName, commentSnippet }),
            { type: 'showcase_comment', showcaseId, projectName },
            { title: `💬 ${commenterName} commented on ${projectName}`, body: commentSnippet || 'New comment on your showcase.' }
        );
    }

    /** GitHub no-commit alert (fires after 8 PM if no commits detected) */
    async sendNoCommitsAlert(userId) {
        const userDoc = await collections.users().doc(userId).get();
        if (!userDoc.exists) return { success: false, error: 'User not found' };
        const user = userDoc.data();

        return this.send(
            userId,
            'github_no_commits',
            () => this.groq.generateNoCommitsAlert({
                userGoal: user.userGoal || 'coding',
                streak: user.streak || 0,
                githubUsername: user.githubUsername || '',
            }),
            { type: 'github_no_commits' },
            { title: '⚡ No Commits Yet Today', body: 'Push at least 1 commit to keep your streak alive!' }
        );
    }

    /** Project revival (repo untouched 2-12 weeks) */
    async sendProjectRevival(userId, projectName, lastPushed) {
        const userDoc = await collections.users().doc(userId).get();
        if (!userDoc.exists) return { success: false, error: 'User not found' };
        const user = userDoc.data();

        return this.send(
            userId,
            'project_revival',
            () => this.groq.generateProjectRevival({ projectName, lastPushed, userGoal: user.userGoal || 'coding' }),
            { type: 'project_revival', projectName, lastPushed: lastPushed || '' },
            { title: `🚀 Remember ${projectName}?`, body: 'It\'s been a while. One commit could reignite the momentum!' }
        );
    }

    /** Task due notification */
    async sendTaskDue(userId, task, dueType = 'today') {
        return this.send(
            userId,
            'task_due',
            () => this.groq.generateTaskDue({ taskTitle: task.title, dueType, priority: task.priority }),
            { type: 'task_due', taskId: task.id || '', taskTitle: task.title, dueType },
            {
                title: dueType === 'today' ? '⚠️ Task Due Today!' : '📌 Task Due Tomorrow',
                body: `"${task.title}" — ${dueType === 'today' ? 'complete it before the day ends' : 'wrap it up tomorrow'}.`,
            }
        );
    }

    /** Break reminder (frequent-commit pattern users, 90min inactivity) */
    async sendBreakReminder(userId, inactiveMinutes = 90) {
        const userDoc = await collections.users().doc(userId).get();
        if (!userDoc.exists) return { success: false, error: 'User not found' };
        const user = userDoc.data();
        const prefs = user.preferences || {};

        if (!prefs.breakDetection) return { success: false, error: 'Break detection disabled' };
        if (prefs.commitPattern !== 'frequent') return { success: false, error: 'Not on frequent pattern' };

        return this.send(
            userId,
            'break_reminder',
            () => this.groq.generateBreakReminder({ inactiveMinutes }),
            { type: 'break_reminder', inactiveMinutes: String(inactiveMinutes) },
            { title: '☕ Taking a Break?', body: `${inactiveMinutes} min of inactivity detected. Log a break!` }
        );
    }

    /** System/admin broadcast to a specific user */
    async sendSystemUpdate(userId, updateTitle, updateDesc) {
        return this.send(
            userId,
            'system_update',
            () => this.groq.generateSystemUpdate({ updateTitle, updateDesc }),
            { type: 'system_update' },
            { title: `🆕 ${updateTitle}`, body: updateDesc || 'DevTrack has been updated. Check it out!' }
        );
    }

    // =========================================================================
    // SCHEDULED CHECKS (called by node-cron)
    // =========================================================================

    /**
     * Cron: Every 5 min — send consistency reminders to eligible users.
     * Respects adaptive (matches lastStartTime) and fixed time modes.
     */
    async checkAndSendReminders() {
        try {
            const now = new Date();
            const currentHour = now.getHours();
            const currentMinute = now.getMinutes();
            const currentTime = `${String(currentHour).padStart(2, '0')}:${String(currentMinute).padStart(2, '0')}`;

            console.log(`⏰ [Reminders] Checking at ${currentTime}`);

            const snapshot = await collections.users()
                .where('fcmToken', '!=', null)
                .get();

            const results = [];

            for (const doc of snapshot.docs) {
                const user = doc.data();
                const prefs = user.preferences || {};

                if (!user.onboardingCompleted) continue;
                if (prefs.notifications === false) continue;

                let shouldSend = false;

                if (prefs.reminderMode === 'fixed' && prefs.fixedTime) {
                    const [fh, fm] = this.parseTime(prefs.fixedTime);
                    if (currentHour === fh && Math.abs(currentMinute - fm) <= 5) shouldSend = true;
                } else {
                    // Adaptive — matches user's last start time
                    if (!user.lastStartTime) continue;
                    const [lh, lm] = user.lastStartTime.split(':').map(Number);
                    if (currentHour === lh && Math.abs(currentMinute - lm) <= 5) shouldSend = true;
                }

                if (shouldSend) {
                    console.log(`📤 Reminder → ${doc.id} (${prefs.reminderMode || 'adaptive'})`);
                    const result = await this.sendConsistencyReminder(doc.id);
                    results.push({ userId: doc.id, ...result });
                }
            }

            return { success: true, checkedAt: currentTime, sent: results.length, results };
        } catch (error) {
            console.error('❌ checkAndSendReminders error:', error.message);
            return { success: false, error: error.message };
        }
    }

    /**
     * Cron: Daily at 8 PM — check for missed activity + project revival.
     */
    async checkDynamicNotifs() {
        try {
            console.log('🔍 [Dynamic] Starting dynamic notification check...');
            const now = new Date();
            const todayStr = now.toISOString().split('T')[0];

            const snapshot = await collections.users().get();
            console.log(`👤 [Dynamic] ${snapshot.docs.length} users to check`);

            for (const doc of snapshot.docs) {
                const userId = doc.id;
                const user = doc.data();
                const prefs = user.preferences || {};

                if (!user.onboardingCompleted) continue;
                if (prefs.notifications === false) continue;

                // 1. Check commits today
                const hasCommits = await this.checkTodayCommits(user, todayStr);

                // 2. Check logs today
                const hasLogs = await this.checkTodayLogs(userId, todayStr);

                if (!hasCommits && !hasLogs) {
                    await this.sendNoCommitsAlert(userId);
                    continue; // Don't stack multiple notifs
                }

                // 3. Project revival check
                const inactiveProject = await this.checkProjectInactivity(user);
                if (inactiveProject) {
                    await this.sendProjectRevival(userId, inactiveProject.name, inactiveProject.lastPushed);
                }
            }

            return { success: true };
        } catch (error) {
            console.error('❌ checkDynamicNotifs error:', error.message);
            return { success: false, error: error.message };
        }
    }

    /**
     * Cron: Daily at 9 AM — check task due dates.
     */
    async checkTasksDue() {
        try {
            console.log('📋 [Tasks] Checking task due dates...');
            const now = new Date();
            const todayStr = now.toISOString().split('T')[0];
            const tomorrow = new Date(now.getTime() + 24 * 60 * 60 * 1000);
            const tomorrowStr = tomorrow.toISOString().split('T')[0];

            const snapshot = await collections.users().get();

            for (const doc of snapshot.docs) {
                const userId = doc.id;
                const user = doc.data();
                if (!user.onboardingCompleted) continue;
                if (user.preferences?.notifications === false) continue;

                try {
                    const tasksSnap = await collections.tasks
                        ? collections.tasks().where('uid', '==', userId).where('priority', '==', 'high').get()
                        : null;

                    if (!tasksSnap) continue;

                    for (const taskDoc of tasksSnap.docs) {
                        const task = { id: taskDoc.id, ...taskDoc.data() };
                        if (!task.dueDate || task.completed) continue;

                        if (task.dueDate === todayStr) {
                            await this.sendTaskDue(userId, task, 'today');
                        } else if (task.dueDate === tomorrowStr) {
                            await this.sendTaskDue(userId, task, 'tomorrow');
                        }
                    }
                } catch (taskError) {
                    // Non-fatal — continue for next user
                }
            }

            return { success: true };
        } catch (error) {
            console.error('❌ checkTasksDue error:', error.message);
            return { success: false, error: error.message };
        }
    }

    /**
     * Cron: Daily at 7 AM — check streak milestones.
     */
    async checkStreakMilestones() {
        try {
            console.log('🏆 [Milestones] Checking streak milestones...');
            const MILESTONE_DAYS = [7, 14, 30, 50, 100];

            const snapshot = await collections.users().get();

            for (const doc of snapshot.docs) {
                const userId = doc.id;
                const user = doc.data();
                if (!user.onboardingCompleted) continue;
                if (user.preferences?.notifications === false) continue;

                const streak = user.streak || 0;
                if (MILESTONE_DAYS.includes(streak)) {
                    await this.sendStreakMilestone(userId, streak);
                }
            }

            return { success: true };
        } catch (error) {
            console.error('❌ checkStreakMilestones error:', error.message);
            return { success: false, error: error.message };
        }
    }

    // =========================================================================
    // TOKEN MANAGEMENT
    // =========================================================================

    async registerToken(userId, token) {
        try {
            await collections.users().doc(userId).set(
                { fcmToken: token, fcmTokenUpdatedAt: new Date().toISOString() },
                { merge: true }
            );
            return { success: true, message: 'Token registered' };
        } catch (error) {
            return { success: false, error: error.message };
        }
    }

    async removeToken(userId) {
        try {
            await collections.users().doc(userId).set(
                { fcmToken: null, fcmTokenUpdatedAt: new Date().toISOString() },
                { merge: true }
            );
            return { success: true, message: 'Token removed' };
        } catch (error) {
            return { success: false, error: error.message };
        }
    }

    // =========================================================================
    // IN-APP NOTIFICATIONS CRUD
    // =========================================================================

    async getUserNotifications(userId, limit = 20) {
        try {
            const userDoc = await collections.users().doc(userId).get();
            if (!userDoc.exists) return { success: false, error: 'User not found' };

            const notifications = (userDoc.data().notifications || []).slice(0, limit);
            const unreadCount = notifications.filter(n => !n.read).length;

            return { success: true, notifications, unreadCount };
        } catch (error) {
            return { success: false, error: error.message };
        }
    }

    async markNotificationRead(userId, notificationId) {
        try {
            const userRef = collections.users().doc(userId);
            const userDoc = await userRef.get();
            if (!userDoc.exists) return { success: false, error: 'User not found' };

            const notifications = (userDoc.data().notifications || []).map(n =>
                n.id === notificationId ? { ...n, read: true } : n
            );

            await userRef.update({ notifications });
            return { success: true };
        } catch (error) {
            return { success: false, error: error.message };
        }
    }

    async markAllNotificationsRead(userId) {
        try {
            const userRef = collections.users().doc(userId);
            const userDoc = await userRef.get();
            if (!userDoc.exists) return { success: false, error: 'User not found' };

            const notifications = (userDoc.data().notifications || []).map(n => ({ ...n, read: true }));
            await userRef.update({ notifications });
            return { success: true };
        } catch (error) {
            return { success: false, error: error.message };
        }
    }

    async deleteNotification(userId, notificationId) {
        try {
            const userRef = collections.users().doc(userId);
            const userDoc = await userRef.get();
            if (!userDoc.exists) return { success: false, error: 'User not found' };

            const notifications = (userDoc.data().notifications || []).filter(n => n.id !== notificationId);
            await userRef.update({ notifications });
            return { success: true };
        } catch (error) {
            return { success: false, error: error.message };
        }
    }

    // =========================================================================
    // GITHUB HELPERS
    // =========================================================================

    async checkTodayCommits(user, todayStr) {
        try {
            if (!user.githubUsername || !user.githubToken) return true;
            const gh = new GitHubService(user.githubToken);
            const activity = await gh.getActivitySummary(user.githubUsername);
            return activity.todayEvents > 0;
        } catch {
            return true; // Fallback to avoid spam
        }
    }

    async checkTodayLogs(userId, todayStr) {
        try {
            const snap = await collections.logs()
                .where('uid', '==', userId)
                .where('date', '==', todayStr)
                .get();
            return !snap.empty;
        } catch {
            return true;
        }
    }

    async checkProjectInactivity(user) {
        try {
            if (!user.githubUsername || !user.githubToken) return null;
            const gh = new GitHubService(user.githubToken);
            const repos = await gh.getRepos(user.githubUsername, 5);
            const now = new Date();
            const twoWeeksAgo = new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000);
            const threeMonthsAgo = new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000);

            for (const repo of repos) {
                const lastPush = new Date(repo.updatedAt);
                if (lastPush < twoWeeksAgo && lastPush > threeMonthsAgo) {
                    return { name: repo.name, lastPushed: repo.updatedAt };
                }
            }
            return null;
        } catch {
            return null;
        }
    }

    // =========================================================================
    // UTILITY
    // =========================================================================

    parseTime(timeStr) {
        if (!timeStr) return [0, 0];
        const ampm = timeStr.match(/(\d{1,2}):(\d{2})\s*(AM|PM)/i);
        if (ampm) {
            let h = parseInt(ampm[1]);
            const m = parseInt(ampm[2]);
            const period = ampm[3].toUpperCase();
            if (period === 'PM' && h !== 12) h += 12;
            if (period === 'AM' && h === 12) h = 0;
            return [h, m];
        }
        const parts = timeStr.split(':').map(Number);
        return [parts[0] || 0, parts[1] || 0];
    }
}

// Singleton
let _instance = null;
const getNotificationService = () => {
    if (!_instance) _instance = new NotificationService();
    return _instance;
};

module.exports = { NotificationService, getNotificationService };
